// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTZbxme7aHr_zdhPHH6sgHzCjJ7lQr6g',
    appId: '1:1047655151970:android:198f88ca581adced98943b',
    messagingSenderId: '1047655151970',
    projectId: 'sear-37cf9',
    storageBucket: 'sear-37cf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI8OlXQDZokh14ra6Sho2ecYT38cfgjUo',
    appId: '1:1047655151970:ios:f70cb89190c6cd3798943b',
    messagingSenderId: '1047655151970',
    projectId: 'sear-37cf9',
    storageBucket: 'sear-37cf9.firebasestorage.app',
    androidClientId: '1047655151970-ls656osggp7qvnju0227cnr0qi9pqii5.apps.googleusercontent.com',
    iosClientId: '1047655151970-ufr9gdub42k81iu49jfloi0nkoql6di8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aaaaa',
  );

}